### ISSUE TITLE
Style needed

### ISSUE THREAD

**Issue by dguis** [D-Multi-cTech/cTechstudios.d-multi.com#1]
I would like recommendations for the style of this site. If you are assigned to this issue, please comment with ideas.

**Comment by dude2093350** [comment]
Hello, I am developing a remodel for this site, also I would like to contact you (privately) regarding a new game development project using LUA, I believe that D-Multi would be an excellent developer for this  project all seven cTechstudios employees will be working on this project:

Project Lead:
Erik Christensen - Director of development
Ezra Diemert - Assistant Director of development

Writing:
Logan - Director or writing, writer
Ezra Diemert - writer

Programming:
Erik Christensen - Director of Programming, Programmer (LUA, C# and JavaScript)
Possibly: DGUIS - Programmer (LUA and JavaScript)

Environment Design:
Names not disclosable, total of six people

**Comment by dude2093350** [comment]
Fix:
Logan - Director OF writing, writer

**Comment by dguis** [comment]
Hello! I would just like to clarify a couple details about this proposal:
1. Would the scripting for this game be made entirely with LUA?
2. Would any other language knowledge be useful? - Most D-Multi developers are only familiar with a few languages including JavaScript and Python. I am curious if these will be useful to the project or if our developers will need to learn the basic of LUA. If that is the case, I am we would be willing to do so, I just wanted to make sure.

I also would like to add that D-Multi Graphic Designers may also be able to assist with the project, and our web designers would be willing to help design a website for the project. If you can get some clarification for the details listed above, that would be great. If you would like to contact D-Multi studios privately, please write to [our support email](mailto:support@d-multi.com). I will get in contact with the rest of the D-Multi team as soon as I can. Thanks!

<a href="https://github.com/dguis"><h6>Dguis - CEO of D-Multi</h6><img src="https://dguis.github.io/RES/New%20Logos/DG50x50db.png"></a>

**Comment by dude2093350** [comment]
Excellent! Great to know, my team is 100% able to do what they need to do. JavaScript is only used for client side but this game is hosted almost completely online (don't worry online services provided by cTechstudios) it would be mostly necessary to learn the Roblox build of LUA: https://developer.roblox.com/api-reference (just since it uses the same items)  and actual LUA:
https://www.lua.org/docs.html

Please note that all copyrights for this game will remain property of cTechstudios and all profits (if generated) will be distributed amongst cTechstudios employees. Also, it may be necessary to install this: 
https://www.roblox.com/create

It may install the roblox player but you don't need to actual use it until the game is hosted using multiplay (multiplay.com) the game will be available through Roblox but not built on their framework (except for backend services) (If you aren't allowed to play Roblox, that is ok since this includes NO player interaction except during beta testing amongst employees.)
